### ISSUE TITLE
Make changes in the program to take input from the user

### ISSUE THREAD

**Issue by dscgecbsp** [dscgecbsp/Voting-Problem-HacktoberFest2022#2]

**Comment by habilyadigar** [comment]
can you assign to me?

**Comment by S-YUVARAJ** [comment]
Hey @dscgecbsp can you assign this issue to me

- Do i have to create a separate file or should i just add the lines in the existing file

- Also can you specify the programming language that needs to be used??

**Comment by Aksbj** [comment]
hello @dscgecbsp can you assighn this issue to me

**Comment by dscgecbsp** [comment]
I assighn this to you @Aksbj

**Comment by Vedant070401** [comment]
assign this to me

**Comment by dscgecbsp** [comment]
i assighn this to @Vedant070401

**Comment by dscgecbsp** [comment]
@S-YUVARAJ you need to create seperate file and you have to code  in Python

**Comment by AmruthaSri852** [comment]
Hello @dscgecbsp Kindly assign the issue to me

**Comment by dscgecbsp** [comment]
Assigned @AmruthaSri852

**Comment by Ayush66325** [comment]
plz assign rhis issue to me @dscgecbsp

**Comment by Deeptan2002** [comment]
plz assign this issue to me @dscgecbsp

**Comment by mohnishjamde** [comment]
can i try solving this problem?

**Comment by swikrit92** [comment]
can you assign this issue to me @dscgecbsp

**Comment by Vikas-sr001** [comment]
please assign this issue to me @dscgecbsp

**Comment by MuskanVerma11** [comment]
Please assign this issue to me @dscgecbsp

**Comment by dscgecbsp** [comment]
I assign this issue to @swikrit92

**Comment by dscgecbsp** [comment]
i assign this issue to @Ayush66325

**Comment by dscgecbsp** [comment]
i assign this issue to @mohnishjamde

**Comment by dscgecbsp** [comment]
i assign this issue to @MuskanVerma11

**Comment by dewanganRachna** [comment]
plz assign this issue to me @dscgecbsp
